Repository UAL-RE/ReQUIAM, pull requests merged in 2021-04, with the labels that each got.

#140 PR/Hotfix: Update Bug Report Template
  .github/ISSUE_TEMPLATE/bug-report.md
  README.md
  requiam/__init__.py
  setup.py
Labels: enhancement, management

#142 Chore: Migrate repository to UAL-ODIS
  README.md
  requiam/__init__.py
  requiam/logger.py
  scripts/add_grouper_groups
  scripts/get_org_code_numbers
  scripts/script_run
  scripts/user_update
  setup.py
Labels: documentation, management

#144 hotfix/v0.16.4
  README.md
  requiam/__init__.py
  requiam/commons.py
  setup.py
Labels: bug

#146 Chore: Refactor using redata-commons
  README.md
  requiam/delta.py
  requiam/git_info.py
  requiam/grouper.py
  requiam/ldap_query.py
  requiam/logger.py
  requiam/manual_override.py
  requirements.txt
  scripts/add_grouper_groups
  scripts/get_org_code_numbers
  scripts/script_run
  scripts/user_update
  tests/test_git_info.py
  tests/test_logger.py
Labels: chore, p1, reorganization, scripts

#147 Add type hinting throughout codebase
  requiam/__init__.py
  requiam/commons.py
  requiam/delta.py
  requiam/grouper.py
  requiam/ldap_query.py
  requiam/manual_override.py
  requiam/org_code_numbers.py
  requiam/quota.py
Labels: documentation, p2

#151 hotfix/v0.16.5
  README.md
  requiam/__init__.py
  requiam/grouper.py
  setup.py
Labels: bug, p1

#149 release/v0.17.0
  README.md
  requiam/__init__.py
  requiam/delta.py
  requiam/git_info.py
  requiam/grouper.py
  requiam/ldap_query.py
  requiam/logger.py
  requiam/manual_override.py
  requirements.txt
  scripts/add_grouper_groups
  scripts/get_org_code_numbers
  scripts/script_run
  scripts/user_update
  setup.py
  tests/test_git_info.py
  tests/test_logger.py
Labels: chore, reorganization, scripts

#153 Bug: Regression from v0.17.0 with pandas_write_buffer
  README.md
  requiam/__init__.py
  scripts/script_run
  setup.py
Labels: bug, scripts
