Repository UAL-RE/ReQUIAM, pull requests merged in 2021-01, with the labels that each got.

#117 feature/87_grouper_refactor
  requiam/commons.py
  requiam/delta.py
  requiam/grouper.py
  requiam/grouper_query.py
  scripts/add_grouper_groups
  scripts/script_run
  scripts/user_update
  tests/test_commons.py
  tests/test_grouper_query.py
Labels: api, enhancement, p2

#124 feature/118_fstrings
  requiam/__init__.py
  requiam/ldap_query.py
  requiam/org_code_numbers.py
Labels: enhancement, p2, pep8, scripts

#125 121_add_ci_testing_for_python_3_9
  .github/workflows/python-package.yml
  requirements.txt
Labels: CI/CD, enhancement
